Ichikawa
camphor-/schedule-notifier pull request #33
Opened 2021-06-13 07:32 UTC by iKerr3721

Makeの日も通知するようにした

2021-06-14 15:02 UTC, KMConner requested changes
ひとまず、Lint (Python のコードが整形されてないと怒ってくれるやつ) が落ちているのでそこを直すのからやってもらったらいいかな

下の checks のところの details を開けば travis CI のページに行けるのでそこから何で怒られてるかを見たらいいかなと

大まかには
- コメントの最初は `#` の後にスペースを入れる
- 関数の前は2行開ける

とかを直したらいいはず

---

それと、テストも書いて欲しくて、

ひとまず１週間分のスケジュールを通知するときのテストを
https://github.com/camphor-/schedule-notifier/blob/master/tests/test_app.py#L232

付近に書いてみてもらえる？

分からなかかったら何でも聞いてくださいー

2021-06-15 16:21 UTC, KMConner commented
master 側を一旦マージした方が良いかも

2021-08-05 13:14 UTC, 5ebec commented
↑気になるところがあるのでWIPで

2021-08-07 07:31 UTC, mitsueda-itsuki approved these changes

2021-08-07 12:44 UTC, 5ebec commented
@mitsueda-itsuki 言ってたところ修正したのでレビューお願いします
@KMConner も良ければ

2021-08-07 13:11 UTC, mitsueda-itsuki commented
差分みました LGTMです！

2021-08-07 13:13 UTC, KMConner approved these changes
PRのタイトルだけ変えといて欲しい

2021-08-07 13:19 UTC, merged